language: python
python:
  - "2.7"
env:
  global:
    - TRAVIS_TAG=2.0.0-dev
    - PWD=$(pwd)
    - TESTPATH=$PWD/resources/lib/tests
    - PROFILEPATH=$PWD/tmp/addon_data
    - DISTPATH=$PWD/tmp/dist
    - PYTHONPATH=$PYTHONPATH:$PWD:$PWD/resources/lib:$PWD/resources/lib/tinydb:$PWD/resources/lib/vk:$TESTPATH:$PROFILEPATH
    - secure: Q9vVY4HIABR8q868GEvklbSQG8FdlpaHkdboxgtVkdfTAXf76Yjojj4RbmH9CXMDNJEILi+2LH8Lk3mAuNb0oFO+hobo27IJwy+dTMGzQZWuVBFFAIKoZg6tVDwYwb0GkgwFFvb+MBv61LgPJxwKak76PzBPTv5IIjK9BtXeiZ+m7IOaTbkZzxqDoK3iET1tPl9BWrQ68RTYsJFQg6YqgOhy8sxd7pp+Tto/hLyvhyS2IcESboRYfkSoiXQozXkQ2vwGsb5PJ7+CnM8Z6Km19OXeaba1hH0lvkdPomJCj5czQTn7nlbsXfL0vDnDEaea0DoSabjCQ6G5pBUVpTKfXf11On3NJ/rOuMX1D7+zI8Rdy7FgUmJYJVPPJRtRP6PZmeKaU3rDJ9VVqORO8Z1QU3ZBi4eadiTp5rsvltDW8A6T4bnCeaKJNV61QkWJR5C/VcvX0X7weiztErOO6DiXAkcUZk5aCIexldNXX1UtJvNedstoztaiJAhWHQVrV5bRG/UbTUN0ShjyNPwZM4iwR0TkMX/dv3Rn4raTfjtTWr0U1aJBPyzr72nGjLtjSRpOZ4d2c+1o3769QYsSVO34BAF1WQ4tti45ehAHhfqpTZvG/H2jv99y503+ptev17t2YFKUAYrkp2+FjqCUkUhohwCHCiTp+UniDrVucu/GBe4=
    - secure: aLhN+b1CE92SHsZ//7Sc68kgC71oVfeQz5J+8H1evSTvvjGxmfzkrsAX4xIRYTqlyz5Y6UTGWu26nahrPUHdtORqd9+/T+UAcv5+owszZzIcGKIwX2Ut8lqWR7aiwRuyMaKKq0i1f/TP3BSNFzSHjAoG4l/ERbKsdixpvYHX4jCwZwCTE7N+xFKjde5uGDC+/4vQBGX2lh1vFlvoOMsVjvyUWmeuqhEtUFaCjf2L79IjP8LeYF976X0ZELoWhbnU0/OVUpQc4x/Cyhnww56iI4f1d/vGGTLXz7DvR+VOTB3hBFTFwtoJ7ZP88L9oQ5+S0gDd77jP4uk8j2yVE18dSBtXrELXU38BGD4cB0hmIyOmhhHK8yVLb9Q0CK8RV2f47KpAHJJ/EpiXSgQBg+EtidHxN0pbH5+jaltBdozqxwBuAhjJNZEheL5dgPz7SUS42zwK5Gu/BBz46mza+/Kete7HHinP7Uzrx7oM5tSB9oDygmwS4Bj4g8VE7LCQBbY6E92LSsN1qiXAdbnLDR5lHRnHPZlNU5XbWPibvA1eRd6lwwdrZXkD+QsGvPd/6gGup2Cp0Dfh4gQAONJ0s0FCS2qHJVPhxvOmEGh1w34krwOJRDrPljzaaUMSGA7rp9ocV011XTNDcCd3SVrk2EtlRsAJf9O8kkl3VHjx9/Ctk/Y=
before_install:
  - echo $PYTHONPATH
install:
  - pip install -r requirements.txt
  - mkdir -p $PROFILEPATH
script:
  - cd $TESTPATH
  - pytest -v -rA
before_deploy:
  - cd $PWD
  - mkdir -p $DISTPATH
  - cp -r addon.xml CHANGELOG.md LICENSE.md README.md resources $DISTPATH
  - rm -r $DISTPATH/resources/lib/tests
  - zip $DISTPATH/plugin.video.vk-$TRAVIS_TAG.zip -r $DISTPATH
  - git config --local user.name "Troikano"
  - git config --local user.email "tdcp87@gmail.com"
  - git tag $TRAVIS_TAG
deploy:
  on:
    repo: Troikano/plugin.video.vk
    branch: master
    tags: true
  provider: releases
  api_key:
    secure: SMyo2FoaAZy/dNd0GXRCsuj7V33F5C65pnzMzlaAx8sfimo8AtBWI+Tyy1OxTGWdNLyfmPoo4mIotAlOTgxlVzZSNAwyUh2++saMNACxJQFexovD1flpKgZ2NUt7gE0jc7zeqMuz7DiPOiAKwQyN0rzbN5e/rZAUerLc5NMG6oWIzghw0/O9BURO24MQBdwpf6U0WHjwe+oozNoj4KWHmRo3WWD9PbUVpL2Kfool3T7QREngn0NSwGmK+gaa1NH8IXMTSx+pTpbggj4vJ7lBXSJFyVdn0mGBSdOJS8xQqdWgxL/gXMk8o+iMAcAU+o7IQP7fTZ5SHxw1Eub7znSdE31lS9jc1nbiav8U65BvV3RoO29ZYmnysYK50Bvidv+9XaPHcJPcg3GOlLUDD7ZIdI7TkET23Qimx/tJemhiY3dAXeRnC6+OV0MMWFYYWtXx52FiQje5i+MkQWZz4X7Y0MgYq1luIqqCc5mwSm/1jZ1s30N9KA4/yiKok1yFNSaf+3SktAfqi5y20z96G+H7tXtb4XmZXig3JlV3mO6f5tCdXakbGC0qB1nxBzHPql5DGavNB2/5STD9j+egUiBVzhir0hnn20OCrEgko5yl0IMW7vLJ9kz4eb7IuhbzlxpwfaGxYyLDMKUgooYcM/H25YO8RPX56WpkrwkAifwQVLw=
  file: $DISTPATH/plugin.video.vk-$TRAVIS_TAG.zip
  skip_cleanup: true
  draft: true
notifications:
  email:
    on_success: always
    on_failure: always
