language: python
python:
  - "3.8"
env:
  global:
    - TRAVIS_TAG=2.0.0-dev
    - PWD=$(pwd)
    - TESTPATH=$PWD/resources/lib/tests
    - PROFILEPATH=$PWD/tmp/addon_data
    - DISTPATH=$PWD/tmp/dist
    - PYTHONPATH=$PYTHONPATH:$PWD:$PWD/resources/lib:$PWD/resources/lib/tinydb:$PWD/resources/lib/vk:$TESTPATH:$PROFILEPATH
    - secure: Q9vVY4HIABR8q868GEvklbSQG8FdlpaHkdboxgtVkdfTAXf76Yjojj4RbmH9CXMDNJEILi+2LH8Lk3mAuNb0oFO+hobo27IJwy+dTMGzQZWuVBFFAIKoZg6tVDwYwb0GkgwFFvb+MBv61LgPJxwKak76PzBPTv5IIjK9BtXeiZ+m7IOaTbkZzxqDoK3iET1tPl9BWrQ68RTYsJFQg6YqgOhy8sxd7pp+Tto/hLyvhyS2IcESboRYfkSoiXQozXkQ2vwGsb5PJ7+CnM8Z6Km19OXeaba1hH0lvkdPomJCj5czQTn7nlbsXfL0vDnDEaea0DoSabjCQ6G5pBUVpTKfXf11On3NJ/rOuMX1D7+zI8Rdy7FgUmJYJVPPJRtRP6PZmeKaU3rDJ9VVqORO8Z1QU3ZBi4eadiTp5rsvltDW8A6T4bnCeaKJNV61QkWJR5C/VcvX0X7weiztErOO6DiXAkcUZk5aCIexldNXX1UtJvNedstoztaiJAhWHQVrV5bRG/UbTUN0ShjyNPwZM4iwR0TkMX/dv3Rn4raTfjtTWr0U1aJBPyzr72nGjLtjSRpOZ4d2c+1o3769QYsSVO34BAF1WQ4tti45ehAHhfqpTZvG/H2jv99y503+ptev17t2YFKUAYrkp2+FjqCUkUhohwCHCiTp+UniDrVucu/GBe4=
    - secure: aLhN+b1CE92SHsZ//7Sc68kgC71oVfeQz5J+8H1evSTvvjGxmfzkrsAX4xIRYTqlyz5Y6UTGWu26nahrPUHdtORqd9+/T+UAcv5+owszZzIcGKIwX2Ut8lqWR7aiwRuyMaKKq0i1f/TP3BSNFzSHjAoG4l/ERbKsdixpvYHX4jCwZwCTE7N+xFKjde5uGDC+/4vQBGX2lh1vFlvoOMsVjvyUWmeuqhEtUFaCjf2L79IjP8LeYF976X0ZELoWhbnU0/OVUpQc4x/Cyhnww56iI4f1d/vGGTLXz7DvR+VOTB3hBFTFwtoJ7ZP88L9oQ5+S0gDd77jP4uk8j2yVE18dSBtXrELXU38BGD4cB0hmIyOmhhHK8yVLb9Q0CK8RV2f47KpAHJJ/EpiXSgQBg+EtidHxN0pbH5+jaltBdozqxwBuAhjJNZEheL5dgPz7SUS42zwK5Gu/BBz46mza+/Kete7HHinP7Uzrx7oM5tSB9oDygmwS4Bj4g8VE7LCQBbY6E92LSsN1qiXAdbnLDR5lHRnHPZlNU5XbWPibvA1eRd6lwwdrZXkD+QsGvPd/6gGup2Cp0Dfh4gQAONJ0s0FCS2qHJVPhxvOmEGh1w34krwOJRDrPljzaaUMSGA7rp9ocV011XTNDcCd3SVrk2EtlRsAJf9O8kkl3VHjx9/Ctk/Y=
before_install:
  - echo $PYTHONPATH
install:
  - pip install -r requirements.txt
  - mkdir -p $PROFILEPATH
script:
  - cd $TESTPATH
  - pytest -v -rA
before_deploy:
  - cd ../../..
  - mkdir -p $DISTPATH
  - cp -r addon.xml CHANGELOG.md LICENSE.md README.md resources $DISTPATH
  - rm -r $DISTPATH/resources/lib/tests
  - zip $DISTPATH/plugin.video.vk-$TRAVIS_TAG.zip -r $DISTPATH
  - git config --local user.name "Troikano"
  - git config --local user.email "tdcp87@gmail.com"
  - git tag $TRAVIS_TAG
deploy:
  on:
    repo: Troikano/plugin.video.vk
    branch: master
    tags: true
  provider: releases
  api_key:
    secure: YKP1GHQOW2kmul8GKGqx9Zho5vueFQa+zjh7U6ljMjVtr3PzDaM7RoukCNQbk8eRtmW8igmKkVv2v3UZcLdZzyfRI660JVnlhVSL04QB4H3yj46gt6lYyKtZtRFAHziQSxVhBeiR3TK6EEBuqk3jCbC28yRy0DXoH6ZFPya+cuHotfNNJVs6If7mF4Job3Rhh0cDKEylowdlfyqG1RzZyj47GPTPtH5iRqHpKZJG/lNyxaDm3QMqRj3l2/Kggp3a4slyWPuxX5ylg4D2BBgonTbpEvmHKvnuTpg81zYTULMD1cGP/sZVmGl4R55nml49MkiEYNWBK727dnOmANfJiIomZiQSeOcW4N5OP/iWv7DQ7uhoVCdSBAZUYHt3BQPPKdalCBdzpv1i18wrfyTdOj/9gQFBkJ9anI7qZWKpTt15LFyEwKVldQF2BhST3t7nAYGWQvi7Uauq3aqdgsOf4vSE0gir8tcPNcbTejbn7TA4onQY8sFVAlzN5wpUV5KPzaxrBo8np7vgglwRITgW2RTWddaQZ1D7ZyRNX6GJ67luW3/mEofhuXGrJFGl4XGcdEFUHTGdtdsXPLO7nTcOrAStmaNmdK9vN99Zs1uMpq0pAV+yrwAnVU0RtQ7GMa3GV2611CQvHsF7Ud4q3w2UoPDtFhkg3jKmPNVWc2geC6E=
  file: $DISTPATH/plugin.video.vk-$TRAVIS_TAG.zip
  skip_cleanup: true
  draft: true
notifications:
  email:
    on_success: always
    on_failure: always
